"""Write `docs/TASKS.md`: what every live task is, from the tasks themselves.

    uv run python scripts/task_index.py

Generated rather than typed, for the reason every generated literal in this
tree is generated: a hand-kept index drifts the first time a key changes,
and it drifts silently because nothing reads it. Everything here comes from
the task's own `task.toml`, `tests/criteria.py`, `tests/oracle.json` and
the floors recorded at build time -- so a stale row means a stale build,
not a stale writer.

Retired tasks are listed separately, with the measurement that retired
them, because the ones that did not work are evidence too.
"""

import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DATASETS = REPO / "datasets"
OUT = REPO / "docs" / "TASKS.md"


def _toml(text: str, key: str) -> str | None:
    match = re.search(rf'^{key}\s*=\s*"""(.*?)"""', text, re.M | re.S)
    if match:
        return " ".join(match.group(1).split())
    match = re.search(rf'^{key}\s*=\s*"([^"]*)"', text, re.M)
    return match.group(1) if match else None


def _retired_note(text: str) -> str:
    """The first sentence of the comment block above `retired = true`."""

    lines = text.splitlines()
    for index, line in enumerate(lines):
        if re.match(r"^retired\s*=\s*true", line):
            note = []
            for above in reversed(lines[:index]):
                if not above.startswith("#"):
                    break
                note.append(above.lstrip("# ").rstrip())
            note.reverse()
            joined = " ".join(n for n in note if n)
            return joined.split(".")[0].strip() + "." if joined else "no reason recorded"
    return "no reason recorded"


def main() -> int:
    live: list[str] = []
    legacy: list[str] = []
    retired: list[str] = []
    certified = (REPO / "docs" / "CERTIFIED.md").read_text()

    for world in sorted(p for p in DATASETS.iterdir() if (p / "tasks").is_dir()):
        for task in sorted((world / "tasks").iterdir()):
            if not task.is_dir() or task.name.startswith("_"):
                continue
            manifest = task / "task.toml"
            if not manifest.is_file():
                continue
            text = manifest.read_text()
            if re.search(r"^retired\s*=\s*true", text, re.M):
                retired.append(
                    f"| `{world.name}/{task.name}` | {_retired_note(text)} |"
                )
                continue
            oracle_path = task / "tests" / "oracle.json"
            criteria_path = task / "tests" / "criteria.py"
            if not (oracle_path.is_file() and criteria_path.is_file()):
                continue
            oracle = json.loads(oracle_path.read_text())
            criteria = criteria_path.read_text()
            # A task whose criteria name no DELIVERABLE cannot be measured
            # by this pipeline at all -- `band.py` refuses it, because a
            # trial that wrote nothing is then indistinguishable from one
            # that answered badly, and the two average differently. Three
            # whole worlds predate the current grading shape and sit here.
            # `^DELIVERABLE`, anchored, exactly as `band.py` looks for it.
            # An unanchored search matches the word in a COMMENT, which put
            # ten tasks in the live table that the pipeline cannot score.
            if not re.search(r"^DELIVERABLE\s*=", criteria, re.M):
                legacy.append(
                    f"| `{world.name}/{task.name}` | "
                    f"{len(oracle.get(next((k for k, v in oracle.items() if isinstance(v, list)), ''), []))} | "
                    "names no DELIVERABLE; the current pipeline cannot score it |"
                )
                continue
            rows_name = next((k for k, v in oracle.items() if isinstance(v, list)), None)
            key = re.search(r"^KEY = \(([^)]*)\)", criteria, re.M)
            key_parts = re.findall(r'"([^"]+)"', key.group(1)) if key else []
            is_certified = f"{task.name} — CERTIFIED" in certified or (
                f"{world.name}/{task.name} — CERTIFIED" in certified
            )
            live.append(
                f"| `{world.name}/{task.name}` | {len(oracle.get(rows_name, []))} | "
                f"{len(key_parts)} — {', '.join(key_parts)} | "
                f"{'yes' if is_certified else 'not yet'} |"
            )

    body = [
        "# Every task in the pack",
        "",
        "Generated by `scripts/task_index.py` from the tasks themselves — their",
        "manifests, criteria and oracles. A stale row here means a stale build.",
        "",
        f"## Live — {len(live)} tasks",
        "",
        "`rows` is the size of the answer key. `key` is what makes a row unique:",
        "every component must be right for the row to count at all, which is",
        "where difficulty lives — a row needing *k* independently-failing facts",
        "is right with probability `a**k`.",
        "",
        "| task | rows | key | certified |",
        "|---|---|---|---|",
        *live,
        "",
        f"## Legacy — {len(legacy)} tasks, not part of the certified pack",
        "",
        "Three worlds -- `ashgrove`, `hartwell`, `calder` -- predate the current",
        "grading architecture. Their criteria name no `DELIVERABLE`, so `band.py`",
        "refuses them: without one, a trial that wrote nothing is indistinguishable",
        "from one that answered badly, and the two average differently.",
        "",
        "They are not merely old. `ashgrove` is the world whose tasks measured at",
        "**~1.000 for a frontier model** however the difficulty was turned up --",
        "rule difficulty survived bounding and coverage did not, and neither moved",
        "the ceiling. That measurement is why `merrick` was recorded, and it is the",
        "reason these are listed rather than counted.",
        "",
        "| task | rows | why not scored |",
        "|---|---|---|",
        *legacy,
        "",
        f"## Retired — {len(retired)} tasks",
        "",
        "Kept with the measurement that retired them. A task that did not work",
        "is evidence about where the surface runs out, and re-deriving that is",
        "more expensive than reading it.",
        "",
        "| task | why |",
        "|---|---|",
        *retired,
        "",
    ]
    OUT.write_text("\n".join(body))
    print(f"  {OUT.relative_to(REPO)}: {len(live)} live, {len(legacy)} legacy, {len(retired)} retired")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
